# Conversion
markdown            : kramdown

# theme
remote_theme        : just-the-docs/just-the-docs

# custom theme settings
color_scheme        : custom
$font-size-2        : 0.75rem

# Markdown Processors
kramdown:
  toc_levels        : [2, 3]
