# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tuflowqgis_check1dIntegrity.ui'
#
# Created: Thu Apr 26 17:28:17 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_check1dIntegrity(object):
    def setupUi(self, check1dIntegrity):
        check1dIntegrity.setObjectName(_fromUtf8("check1dIntegrity"))
        check1dIntegrity.resize(421, 665)
        check1dIntegrity.setFocusPolicy(QtCore.Qt.NoFocus)
        check1dIntegrity.setModal(False)
        self.buttonBox = QtGui.QDialogButtonBox(check1dIntegrity)
        self.buttonBox.setGeometry(QtCore.QRect(210, 632, 201, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label = QtGui.QLabel(check1dIntegrity)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(check1dIntegrity)
        self.label_2.setGeometry(QtCore.QRect(10, 135, 141, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.groupBox = QtGui.QGroupBox(check1dIntegrity)
        self.groupBox.setGeometry(QtCore.QRect(10, 260, 401, 251))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.check1dPoint_cb = QtGui.QCheckBox(self.groupBox)
        self.check1dPoint_cb.setGeometry(QtCore.QRect(210, 20, 161, 20))
        self.check1dPoint_cb.setObjectName(_fromUtf8("check1dPoint_cb"))
        self.check1dLine_cb = QtGui.QCheckBox(self.groupBox)
        self.check1dLine_cb.setGeometry(QtCore.QRect(10, 20, 181, 20))
        self.check1dLine_cb.setObjectName(_fromUtf8("check1dLine_cb"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(5, 115, 181, 124))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.dem_combo = QtGui.QComboBox(self.groupBox_3)
        self.dem_combo.setEnabled(False)
        self.dem_combo.setGeometry(QtCore.QRect(15, 95, 151, 22))
        self.dem_combo.setObjectName(_fromUtf8("dem_combo"))
        self.getDsConnection_cb = QtGui.QCheckBox(self.groupBox_3)
        self.getDsConnection_cb.setEnabled(False)
        self.getDsConnection_cb.setGeometry(QtCore.QRect(3, 2, 181, 20))
        self.getDsConnection_cb.setObjectName(_fromUtf8("getDsConnection_cb"))
        self.getGroundElev_cb = QtGui.QCheckBox(self.groupBox_3)
        self.getGroundElev_cb.setEnabled(False)
        self.getGroundElev_cb.setGeometry(QtCore.QRect(10, 76, 181, 20))
        self.getGroundElev_cb.setObjectName(_fromUtf8("getGroundElev_cb"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setEnabled(False)
        self.label_3.setGeometry(QtCore.QRect(12, 20, 101, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.name1d_combo = QtGui.QComboBox(self.groupBox_3)
        self.name1d_combo.setEnabled(False)
        self.name1d_combo.setGeometry(QtCore.QRect(10, 39, 151, 22))
        self.name1d_combo.setObjectName(_fromUtf8("name1d_combo"))
        self.plotDsConn_cb = QtGui.QCheckBox(self.groupBox_3)
        self.plotDsConn_cb.setEnabled(False)
        self.plotDsConn_cb.setGeometry(QtCore.QRect(10, 60, 181, 20))
        self.plotDsConn_cb.setObjectName(_fromUtf8("plotDsConn_cb"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(5, 41, 181, 71))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.autoSnap_cb = QtGui.QCheckBox(self.groupBox_4)
        self.autoSnap_cb.setEnabled(False)
        self.autoSnap_cb.setGeometry(QtCore.QRect(5, 2, 161, 20))
        self.autoSnap_cb.setObjectName(_fromUtf8("autoSnap_cb"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QtCore.QRect(15, 20, 131, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.snapSearchDis_sb = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.snapSearchDis_sb.setEnabled(False)
        self.snapSearchDis_sb.setGeometry(QtCore.QRect(15, 38, 71, 22))
        self.snapSearchDis_sb.setDecimals(4)
        self.snapSearchDis_sb.setMinimum(0.0001)
        self.snapSearchDis_sb.setObjectName(_fromUtf8("snapSearchDis_sb"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(QtCore.QRect(205, 41, 171, 131))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.correctPipeDir_cb = QtGui.QCheckBox(self.groupBox_6)
        self.correctPipeDir_cb.setEnabled(False)
        self.correctPipeDir_cb.setGeometry(QtCore.QRect(5, 1, 161, 20))
        self.correctPipeDir_cb.setObjectName(_fromUtf8("correctPipeDir_cb"))
        self.usInvField_combo = QtGui.QComboBox(self.groupBox_6)
        self.usInvField_combo.setEnabled(False)
        self.usInvField_combo.setGeometry(QtCore.QRect(11, 34, 151, 22))
        self.usInvField_combo.setObjectName(_fromUtf8("usInvField_combo"))
        self.label_5 = QtGui.QLabel(self.groupBox_6)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(12, 18, 101, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_6)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(11, 55, 121, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.dsInvField_combo = QtGui.QComboBox(self.groupBox_6)
        self.dsInvField_combo.setEnabled(False)
        self.dsInvField_combo.setGeometry(QtCore.QRect(10, 71, 151, 22))
        self.dsInvField_combo.setObjectName(_fromUtf8("dsInvField_combo"))
        self.label_7 = QtGui.QLabel(self.groupBox_6)
        self.label_7.setEnabled(False)
        self.label_7.setGeometry(QtCore.QRect(10, 96, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.groupBox_2 = QtGui.QGroupBox(check1dIntegrity)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 520, 401, 111))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.outSel_cb = QtGui.QCheckBox(self.groupBox_2)
        self.outSel_cb.setGeometry(QtCore.QRect(205, 20, 151, 20))
        self.outSel_cb.setObjectName(_fromUtf8("outSel_cb"))
        self.outMessBox_cb = QtGui.QCheckBox(self.groupBox_2)
        self.outMessBox_cb.setGeometry(QtCore.QRect(15, 20, 171, 20))
        self.outMessBox_cb.setObjectName(_fromUtf8("outMessBox_cb"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(9, 43, 381, 51))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.outTxtFile_cb = QtGui.QCheckBox(self.groupBox_5)
        self.outTxtFile_cb.setGeometry(QtCore.QRect(6, 2, 221, 20))
        self.outTxtFile_cb.setObjectName(_fromUtf8("outTxtFile_cb"))
        self.outFile = QtGui.QLineEdit(self.groupBox_5)
        self.outFile.setEnabled(False)
        self.outFile.setGeometry(QtCore.QRect(6, 23, 291, 22))
        self.outFile.setObjectName(_fromUtf8("outFile"))
        self.browse_button = QtGui.QPushButton(self.groupBox_5)
        self.browse_button.setEnabled(False)
        self.browse_button.setGeometry(QtCore.QRect(302, 23, 71, 21))
        self.browse_button.setObjectName(_fromUtf8("browse_button"))
        self.addLine_combo = QtGui.QComboBox(check1dIntegrity)
        self.addLine_combo.setGeometry(QtCore.QRect(10, 30, 291, 22))
        self.addLine_combo.setObjectName(_fromUtf8("addLine_combo"))
        self.addLine_button = QtGui.QPushButton(check1dIntegrity)
        self.addLine_button.setGeometry(QtCore.QRect(306, 30, 51, 21))
        self.addLine_button.setObjectName(_fromUtf8("addLine_button"))
        self.addPoint_combo = QtGui.QComboBox(check1dIntegrity)
        self.addPoint_combo.setGeometry(QtCore.QRect(10, 153, 291, 22))
        self.addPoint_combo.setObjectName(_fromUtf8("addPoint_combo"))
        self.lineLyrs_lw = QtGui.QListWidget(check1dIntegrity)
        self.lineLyrs_lw.setGeometry(QtCore.QRect(10, 60, 401, 71))
        self.lineLyrs_lw.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.lineLyrs_lw.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lineLyrs_lw.setObjectName(_fromUtf8("lineLyrs_lw"))
        self.pointLyrs_lw = QtGui.QListWidget(check1dIntegrity)
        self.pointLyrs_lw.setGeometry(QtCore.QRect(10, 183, 401, 71))
        self.pointLyrs_lw.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.pointLyrs_lw.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.pointLyrs_lw.setObjectName(_fromUtf8("pointLyrs_lw"))
        self.removeLine_button = QtGui.QPushButton(check1dIntegrity)
        self.removeLine_button.setGeometry(QtCore.QRect(360, 30, 51, 21))
        self.removeLine_button.setObjectName(_fromUtf8("removeLine_button"))
        self.removePoint_button = QtGui.QPushButton(check1dIntegrity)
        self.removePoint_button.setGeometry(QtCore.QRect(360, 154, 51, 21))
        self.removePoint_button.setObjectName(_fromUtf8("removePoint_button"))
        self.addPoint_button = QtGui.QPushButton(check1dIntegrity)
        self.addPoint_button.setGeometry(QtCore.QRect(306, 154, 51, 21))
        self.addPoint_button.setObjectName(_fromUtf8("addPoint_button"))

        self.retranslateUi(check1dIntegrity)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), check1dIntegrity.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), check1dIntegrity.reject)
        QtCore.QMetaObject.connectSlotsByName(check1dIntegrity)

    def retranslateUi(self, check1dIntegrity):
        check1dIntegrity.setWindowTitle(_translate("check1dIntegrity", "Check 1D Network Integrity", None))
        self.label.setText(_translate("check1dIntegrity", "1D network Line Layer", None))
        self.label_2.setText(_translate("check1dIntegrity", "1D network Point Layer", None))
        self.groupBox.setTitle(_translate("check1dIntegrity", "Integrity Options", None))
        self.check1dPoint_cb.setText(_translate("check1dIntegrity", "Check 1D Point-Line snapping", None))
        self.check1dLine_cb.setText(_translate("check1dIntegrity", "Check 1D Line-Line snapping", None))
        self.getDsConnection_cb.setText(_translate("check1dIntegrity", "Get downstream connections", None))
        self.getGroundElev_cb.setText(_translate("check1dIntegrity", "Get ground elevations", None))
        self.label_3.setText(_translate("check1dIntegrity", "Starting at element:", None))
        self.plotDsConn_cb.setText(_translate("check1dIntegrity", "Plot output in TUPLOT", None))
        self.autoSnap_cb.setText(_translate("check1dIntegrity", "Auto snap ", None))
        self.label_4.setText(_translate("check1dIntegrity", "Search radius (map units)", None))
        self.correctPipeDir_cb.setText(_translate("check1dIntegrity", "Correct pipe direction", None))
        self.label_5.setText(_translate("check1dIntegrity", "Upstream Invert field", None))
        self.label_6.setText(_translate("check1dIntegrity", "Downstream Invert field", None))
        self.label_7.setText(_translate("check1dIntegrity", "*Note if using multiple input network layers, the invert fields must be identical for all", None))
        self.groupBox_2.setTitle(_translate("check1dIntegrity", "Output Options", None))
        self.outSel_cb.setText(_translate("check1dIntegrity", "Output as selection", None))
        self.outMessBox_cb.setText(_translate("check1dIntegrity", "Output to message box", None))
        self.outTxtFile_cb.setText(_translate("check1dIntegrity", "Output to txt file", None))
        self.browse_button.setText(_translate("check1dIntegrity", "Browse", None))
        self.addLine_button.setText(_translate("check1dIntegrity", "Add", None))
        self.removeLine_button.setText(_translate("check1dIntegrity", "Remove", None))
        self.removePoint_button.setText(_translate("check1dIntegrity", "Remove", None))
        self.addPoint_button.setText(_translate("check1dIntegrity", "Add", None))

