# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tuflowqgis_bridge_editor.ui'
#
# Created: Sun Jul 01 16:55:02 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_tuflowqgis_BridgeEditor(object):
    def setupUi(self, tuflowqgis_BridgeEditor):
        tuflowqgis_BridgeEditor.setObjectName(_fromUtf8("tuflowqgis_BridgeEditor"))
        tuflowqgis_BridgeEditor.resize(943, 911)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.bridgeEditor_Layout = QtGui.QVBoxLayout()
        self.bridgeEditor_Layout.setObjectName(_fromUtf8("bridgeEditor_Layout"))
        self.bridgeProperties = QtGui.QHBoxLayout()
        self.bridgeProperties.setObjectName(_fromUtf8("bridgeProperties"))
        self.bridgeInputs = QtGui.QGridLayout()
        self.bridgeInputs.setObjectName(_fromUtf8("bridgeInputs"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.bridgeInputs.addWidget(self.label_2, 12, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.bridgeInputs.addWidget(self.label, 11, 0, 1, 4)
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.bridgeInputs.addWidget(self.doubleSpinBox_7, 12, 1, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.tab)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.bridgeInputs.addWidget(self.comboBox_2, 6, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.bridgeInputs.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.bridgeInputs.addWidget(self.label_6, 10, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.bridgeInputs.addWidget(self.label_5, 1, 0, 2, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.bridgeInputs.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.bridgeInputs.addWidget(self.label_10, 9, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.bridgeInputs.addWidget(self.label_13, 8, 0, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.bridgeInputs.addWidget(self.doubleSpinBox_2, 8, 1, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.tab)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.bridgeInputs.addWidget(self.spinBox, 4, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.bridgeInputs.addWidget(self.label_12, 6, 0, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.bridgeInputs.addWidget(self.doubleSpinBox, 5, 1, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.bridgeInputs.addWidget(self.doubleSpinBox_3, 9, 1, 1, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.bridgeInputs.addWidget(self.doubleSpinBox_4, 10, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.bridgeInputs.addWidget(self.label_11, 7, 0, 1, 4)
        self.label_7 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.bridgeInputs.addWidget(self.label_7, 3, 0, 1, 4)
        self.demComboBox = QtGui.QComboBox(self.tab)
        self.demComboBox.setObjectName(_fromUtf8("demComboBox"))
        self.bridgeInputs.addWidget(self.demComboBox, 1, 1, 2, 2)
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.bridgeInputs.addWidget(self.label_14, 4, 2, 1, 2)
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.bridgeInputs.addWidget(self.label_15, 5, 2, 1, 2)
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setIconSize(QtCore.QSize(15, 15))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.bridgeInputs.addWidget(self.pushButton_2, 1, 4, 2, 1)
        self.radioButton = QtGui.QRadioButton(self.tab)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.bridgeInputs.addWidget(self.radioButton, 8, 4, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.tab)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.bridgeInputs.addWidget(self.radioButton_2, 9, 4, 1, 1)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setIconSize(QtCore.QSize(15, 15))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.bridgeInputs.addWidget(self.pushButton, 1, 3, 2, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.tab)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.bridgeInputs.addWidget(self.spinBox_2, 10, 4, 1, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.bridgeInputs.addWidget(self.doubleSpinBox_5, 4, 4, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.bridgeInputs.addWidget(self.label_17, 8, 2, 2, 2)
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
        self.bridgeInputs.addWidget(self.doubleSpinBox_6, 5, 4, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.bridgeInputs.addWidget(self.label_16, 10, 2, 1, 2)
        self.label_32 = QtGui.QLabel(self.tab)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.bridgeInputs.addWidget(self.label_32, 0, 0, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.tab)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.bridgeInputs.addWidget(self.lineEdit_15, 0, 1, 1, 3)
        self.pushButton_5 = QtGui.QPushButton(self.tab)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.bridgeInputs.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.bridgeInputs.setColumnStretch(0, 10)
        self.bridgeInputs.setColumnStretch(1, 10)
        self.bridgeInputs.setColumnStretch(2, 10)
        self.bridgeInputs.setColumnStretch(3, 10)
        self.bridgeInputs.setRowStretch(2, 10)
        self.bridgeInputs.setRowStretch(3, 10)
        self.bridgeInputs.setRowStretch(4, 10)
        self.bridgeInputs.setRowStretch(5, 10)
        self.bridgeInputs.setRowStretch(6, 10)
        self.bridgeInputs.setRowStretch(7, 10)
        self.bridgeInputs.setRowStretch(8, 10)
        self.bridgeInputs.setRowStretch(9, 10)
        self.bridgeInputs.setRowStretch(10, 10)
        self.bridgeInputs.setRowStretch(11, 10)
        self.bridgeInputs.setRowStretch(12, 10)
        self.bridgeProperties.addLayout(self.bridgeInputs)
        self.bridgeTables = QtGui.QGridLayout()
        self.bridgeTables.setObjectName(_fromUtf8("bridgeTables"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.XSectionTable = QtGui.QTableWidget(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.XSectionTable.setFont(font)
        self.XSectionTable.setColumnCount(2)
        self.XSectionTable.setObjectName(_fromUtf8("XSectionTable"))
        self.XSectionTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.XSectionTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.XSectionTable.setHorizontalHeaderItem(1, item)
        self.horizontalLayout.addWidget(self.XSectionTable)
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.tabWidget_2.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.tabWidget_2.addTab(self.tab_9, _fromUtf8(""))
        self.bridgeTables.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.bridgeProperties.addLayout(self.bridgeTables)
        self.bridgeProperties.setStretch(0, 10)
        self.bridgeProperties.setStretch(1, 5)
        self.bridgeEditor_Layout.addLayout(self.bridgeProperties)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame_for_plot_2 = QtGui.QFrame(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_for_plot_2.sizePolicy().hasHeightForWidth())
        self.frame_for_plot_2.setSizePolicy(sizePolicy)
        self.frame_for_plot_2.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_for_plot_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_for_plot_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_for_plot_2.setObjectName(_fromUtf8("frame_for_plot_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_for_plot_2)
        self.verticalLayout_10.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pbUpdate = QtGui.QPushButton(self.frame_for_plot_2)
        self.pbUpdate.setObjectName(_fromUtf8("pbUpdate"))
        self.gridLayout_5.addWidget(self.pbUpdate, 0, 0, 1, 1)
        self.cbShowLegend_2 = QtGui.QCheckBox(self.frame_for_plot_2)
        self.cbShowLegend_2.setObjectName(_fromUtf8("cbShowLegend_2"))
        self.gridLayout_5.addWidget(self.cbShowLegend_2, 0, 1, 1, 1)
        self.cbLegendUL_2 = QtGui.QCheckBox(self.frame_for_plot_2)
        self.cbLegendUL_2.setObjectName(_fromUtf8("cbLegendUL_2"))
        self.gridLayout_5.addWidget(self.cbLegendUL_2, 0, 2, 1, 1)
        self.cbLegendUR_2 = QtGui.QCheckBox(self.frame_for_plot_2)
        self.cbLegendUR_2.setObjectName(_fromUtf8("cbLegendUR_2"))
        self.gridLayout_5.addWidget(self.cbLegendUR_2, 0, 3, 1, 1)
        self.cbLegendLL_2 = QtGui.QCheckBox(self.frame_for_plot_2)
        self.cbLegendLL_2.setObjectName(_fromUtf8("cbLegendLL_2"))
        self.gridLayout_5.addWidget(self.cbLegendLL_2, 0, 4, 1, 1)
        self.cbLegendLR_2 = QtGui.QCheckBox(self.frame_for_plot_2)
        self.cbLegendLR_2.setObjectName(_fromUtf8("cbLegendLR_2"))
        self.gridLayout_5.addWidget(self.cbLegendLR_2, 0, 5, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_5)
        self.gridLayout_3.addWidget(self.frame_for_plot_2, 0, 0, 1, 1)
        self.bridgeEditor_Layout.addLayout(self.gridLayout_3)
        self.frame_for_toolbar = QtGui.QFrame(self.tab)
        self.frame_for_toolbar.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_for_toolbar.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_for_toolbar.setObjectName(_fromUtf8("frame_for_toolbar"))
        self.bridgeEditor_Layout.addWidget(self.frame_for_toolbar)
        self.bridgeEditor_Layout.setStretch(0, 7)
        self.bridgeEditor_Layout.setStretch(1, 15)
        self.bridgeEditor_Layout.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.bridgeEditor_Layout)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 581, 517))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 11, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 12, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 9, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_4.addWidget(self.label_19, 8, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_4.addWidget(self.label_28, 10, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_4.addWidget(self.label_20, 7, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_4.addWidget(self.label_21, 6, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_4.addWidget(self.label_22, 5, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_4.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_4.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_4.addWidget(self.lineEdit_4, 4, 1, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_4.addWidget(self.lineEdit_5, 5, 1, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout_4.addWidget(self.lineEdit_7, 7, 1, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_4.addWidget(self.lineEdit_6, 6, 1, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_4.addWidget(self.lineEdit_13, 13, 1, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_4.addWidget(self.lineEdit_11, 11, 1, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_4.addWidget(self.lineEdit_10, 10, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_4.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_4.addWidget(self.lineEdit_12, 12, 1, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_4.addWidget(self.lineEdit_8, 8, 1, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_4.addWidget(self.lineEdit_9, 9, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 13, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_4.addWidget(self.pushButton_4, 17, 0, 1, 2)
        self.label_29 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_29.setText(_fromUtf8(""))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_4.addWidget(self.label_29, 14, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 3, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_4.addWidget(self.label_30, 15, 0, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_4.addWidget(self.lineEdit_14, 16, 0, 1, 2)
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_4.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_4.addWidget(self.label_31, 7, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        tuflowqgis_BridgeEditor.setWidget(self.dockWidgetContents)

        self.retranslateUi(tuflowqgis_BridgeEditor)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tuflowqgis_BridgeEditor)

    def retranslateUi(self, tuflowqgis_BridgeEditor):
        tuflowqgis_BridgeEditor.setWindowTitle(_translate("tuflowqgis_BridgeEditor", "Bridge Editor", None))
        self.label_2.setText(_translate("tuflowqgis_BridgeEditor", "Zsh Line Width (m)", None))
        self.label.setText(_translate("tuflowqgis_BridgeEditor", "Z Shape Properties", None))
        self.label_9.setText(_translate("tuflowqgis_BridgeEditor", "Pier Thickness (m)", None))
        self.label_6.setText(_translate("tuflowqgis_BridgeEditor", "Hand Rail Height (m)", None))
        self.label_5.setText(_translate("tuflowqgis_BridgeEditor", "DEM", None))
        self.label_8.setText(_translate("tuflowqgis_BridgeEditor", "Number of Piers", None))
        self.label_10.setText(_translate("tuflowqgis_BridgeEditor", "Deck Thickness (m)", None))
        self.label_13.setText(_translate("tuflowqgis_BridgeEditor", "Deck Elevation (Bottom) m RL", None))
        self.label_12.setText(_translate("tuflowqgis_BridgeEditor", "Pier Shape (see pier type tab)", None))
        self.label_11.setText(_translate("tuflowqgis_BridgeEditor", "Deck", None))
        self.label_7.setText(_translate("tuflowqgis_BridgeEditor", "Piers", None))
        self.label_14.setText(_translate("tuflowqgis_BridgeEditor", "Width From Left (m)", None))
        self.label_15.setText(_translate("tuflowqgis_BridgeEditor", "Width From Right (m)", None))
        self.pushButton_2.setText(_translate("tuflowqgis_BridgeEditor", "Use Vector Layer", None))
        self.radioButton.setText(_translate("tuflowqgis_BridgeEditor", "Drowned", None))
        self.radioButton_2.setText(_translate("tuflowqgis_BridgeEditor", "Pressurised", None))
        self.pushButton.setText(_translate("tuflowqgis_BridgeEditor", "Draw XSection", None))
        self.label_17.setText(_translate("tuflowqgis_BridgeEditor", "Flow at Deck", None))
        self.label_16.setText(_translate("tuflowqgis_BridgeEditor", "Hand Rail Blockage", None))
        self.label_32.setText(_translate("tuflowqgis_BridgeEditor", "Bridge Name (Optional)", None))
        self.pushButton_5.setText(_translate("tuflowqgis_BridgeEditor", "Save", None))
        item = self.XSectionTable.horizontalHeaderItem(0)
        item.setText(_translate("tuflowqgis_BridgeEditor", "Offset", None))
        item = self.XSectionTable.horizontalHeaderItem(1)
        item.setText(_translate("tuflowqgis_BridgeEditor", "Elevation", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("tuflowqgis_BridgeEditor", "XSection", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("tuflowqgis_BridgeEditor", "Piers", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("tuflowqgis_BridgeEditor", "Deck", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("tuflowqgis_BridgeEditor", "Hand Rails", None))
        self.pbUpdate.setText(_translate("tuflowqgis_BridgeEditor", "UPDATE PLOT", None))
        self.cbShowLegend_2.setText(_translate("tuflowqgis_BridgeEditor", "Legend", None))
        self.cbLegendUL_2.setText(_translate("tuflowqgis_BridgeEditor", "UL", None))
        self.cbLegendUR_2.setText(_translate("tuflowqgis_BridgeEditor", "UR", None))
        self.cbLegendLL_2.setText(_translate("tuflowqgis_BridgeEditor", "LL", None))
        self.cbLegendLR_2.setText(_translate("tuflowqgis_BridgeEditor", "LR", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("tuflowqgis_BridgeEditor", "Geometry", None))
        self.label_23.setText(_translate("tuflowqgis_BridgeEditor", "dZ", None))
        self.label_26.setText(_translate("tuflowqgis_BridgeEditor", "Layer 3 Depth", None))
        self.label_27.setText(_translate("tuflowqgis_BridgeEditor", "Layer 3 % Blockage", None))
        self.label_18.setText(_translate("tuflowqgis_BridgeEditor", "Layer 2 % Blockage", None))
        self.label_19.setText(_translate("tuflowqgis_BridgeEditor", "Layer 2 Depth", None))
        self.label_28.setText(_translate("tuflowqgis_BridgeEditor", "Layer 2 FLC", None))
        self.label_20.setText(_translate("tuflowqgis_BridgeEditor", "Layer 1 FLC", None))
        self.label_21.setText(_translate("tuflowqgis_BridgeEditor", "Layer 1 % Blockage", None))
        self.label_22.setText(_translate("tuflowqgis_BridgeEditor", "Layer 1 Obvert", None))
        self.label_4.setText(_translate("tuflowqgis_BridgeEditor", "Layer 3 FLC", None))
        self.pushButton_4.setText(_translate("tuflowqgis_BridgeEditor", "Auto Create 2d_lfcsh layer", None))
        self.label_24.setText(_translate("tuflowqgis_BridgeEditor", "Shape Width", None))
        self.label_30.setText(_translate("tuflowqgis_BridgeEditor", "Empty Directory", None))
        self.label_25.setText(_translate("tuflowqgis_BridgeEditor", "Shape Options", None))
        self.label_3.setText(_translate("tuflowqgis_BridgeEditor", "Invert", None))
        self.pushButton_3.setText(_translate("tuflowqgis_BridgeEditor", "Update", None))
        self.label_31.setText(_translate("tuflowqgis_BridgeEditor", "Based on Hydraulics of Bridge Waterways (FHWA, 1978)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("tuflowqgis_BridgeEditor", "Output", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("tuflowqgis_BridgeEditor", "Pier Arrangement Types", None))

